// Supabase Database Types
// This file will be auto-generated by Supabase CLI in production
// For now, we define them manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      mood_entries: {
        Row: {
          id: string;
          user_id: string;
          mood_type: 'great' | 'good' | 'neutral' | 'bad' | 'terrible';
          mood_score: number;
          note: string | null;
          activities: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          mood_type: 'great' | 'good' | 'neutral' | 'bad' | 'terrible';
          mood_score: number;
          note?: string | null;
          activities?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          mood_type?: 'great' | 'good' | 'neutral' | 'bad' | 'terrible';
          mood_score?: number;
          note?: string | null;
          activities?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

